LOAD DATA INFILE 'customers.csv'
INTO TABLE customers
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

LOAD DATA INFILE 'restaurants.csv'
INTO TABLE restaurants
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

LOAD DATA INFILE 'delivery_partners.csv'
INTO TABLE delivery_partners
FIELDS TERMINATED BY ','
IGNORE 1 LINES;

LOAD DATA INFILE 'orders.csv'
INTO TABLE orders
FIELDS TERMINATED BY ','
IGNORE 1 LINES;
